/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package org.devopsfordefense.githubpackageregtest;

import java.util.HashMap;
import java.util.LinkedList;
import java.util.List;
import java.util.Map;

public class Library {

    private List<String> books;
    private Map<String, String> bookAuthor;

    public Library() {
        books = new LinkedList<>();
        bookAuthor = new HashMap<>();
    }
    public boolean addBook(String title, String author) {
        if (books.contains(title)) {
            return false;
        }
        books.add(title);
        bookAuthor.put(title, author);
        return true;
    }
    
    public boolean removeBook(String title) {
        if (!books.contains(title)) {
            return false;
        }
        books.remove(title);
        bookAuthor.remove(title);
        return true;
    }

    public String getBooks() {
        StringBuffer retVal = new StringBuffer();

        boolean first = true;
        for (String title : books) {
            String author = bookAuthor.get(title);

            if (first) {
                first = false;
            } else {
                retVal.append("\n");
            }
            retVal.append(title).append(" by ").append(author);
        }

        return retVal.toString();
    }
}
