/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package org.devopsfordefense.githubpackageregtest;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class LibraryTest {
    @Test void testAddBook() {
        Library classUnderTest = new Library();
        assertTrue(classUnderTest.addBook("Hamlet", "Shakespear"), "addBook should return 'true' for new book");
        assertFalse(classUnderTest.addBook("Hamlet", "Shakespear"), "addBook should return 'false' for existing book");
    }

    @Test void testRemoveBook() {
        Library classUnderTest = new Library();
        classUnderTest.addBook("Hamlet", "Shakespear");
        assertTrue(classUnderTest.removeBook("Hamlet"), "removeBook should return 'true' for existing book");
        assertFalse(classUnderTest.removeBook("Moby Dick"), "removeBook should return 'false' for existing book");
    }

    @Test void testgetBooks() {
        Library classUnderTest = new Library();
        assertTrue(classUnderTest.getBooks().length() == 0);
        classUnderTest.addBook("Hamlet", "Shakespear");
        assertTrue(classUnderTest.getBooks().contains("Hamlet"));
        assertTrue(classUnderTest.getBooks().contains("Shakespear"));
        assertFalse(classUnderTest.getBooks().contains("\n"));
        
        classUnderTest.addBook("Moby Dick", "Herman Melvile");
        assertTrue(classUnderTest.getBooks().contains("Hamlet"));
        assertTrue(classUnderTest.getBooks().contains("Shakespear"));
        assertTrue(classUnderTest.getBooks().contains("\n"));
        assertTrue(classUnderTest.getBooks().contains("Moby Dick"));
        assertTrue(classUnderTest.getBooks().contains("Herman Melvile"));
    }

    @Test void testgetAuthors() {
        Library classUnderTest = new Library();
        assertTrue(classUnderTest.getAuthors().length() == 0);
        classUnderTest.addBook("Hamlet", "Shakespear");
        assertTrue(classUnderTest.getAuthors().contains("Shakespear"));
        assertFalse(classUnderTest.getAuthors().contains("\n"));
        
        classUnderTest.addBook("Moby Dick", "Herman Melvile");
        assertTrue(classUnderTest.getAuthors().contains("Shakespear"));
        assertTrue(classUnderTest.getAuthors().contains("\n"));
        assertTrue(classUnderTest.getAuthors().contains("Herman Melvile"));
    }
}
